import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/Sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex h-screen bg-gray-800">
          <Sidebar />
          <div className="flex-1 p-6 bg-gray-800 text-white min-h-screen">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
